### ISSUE TITLE
Написать функцию get_zeroes()

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#10]
### Todo

- [x] создать модуль
- [x] написать базовый тест
- [ ] написать саму функцию
- [ ] написать более сложные тесты

### Описание

Эта функция должна генерировать строки, состоящие из определённого количества нулей. Она затем будет использоваться на этапе сшивки полного байт-кода бота из отдельных фрагментов (в функции `get_byte_code()`).

Прототип:

``` c
char	*get_zeroes(unsigned int n_zeroes);
```

**Comment by beskaska** [comment]
Закрываю задачу из-за неактуальности.

**Comment by CptnGreen** [comment]
@beskaska, на самом деле может и пригодиться. Там же большие фрагменты с заполняющими нулями, так что может лучше и выделить эту операцию в отдельную фунцию, чтобы не колбасить циклы в другом месте.

**Comment by beskaska** [comment]
@CptnGreen пока пусть повисит здесь. Думаю не понадобиться, потому что при инициализации структуру в `main()`, мы будем заполнять его нулями (тот же `ft_memset()`).

**Comment by CptnGreen** [comment]
@beskaska, да, теперь вижу, что не пригодитя
