### ISSUE TITLE
Написать функцию chars_to_bytes()

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#13]
### Todo

- [x] удалить модули для get_comment() и для get_name() [CptnGreen]
- [x] создать модуль для chars_to_bytes() [CptnGreen]
- [x] написать базовый тест [CptnGreen]
- [ ] написать саму функцию
- [ ] написать дополнительные тесты

### Описание

Эта функция должна принимать текстовую строку и возвращать эту же строку, переведённую в байт-код. Заполняющие (до нужной длины строки) нули в возвращаемую строку включать не нужно. Прототип:
``` c
char	*chars_to_bytes(char const *comment);
```

**Comment by CptnGreen** [comment]
Есть подозрение, что этот тикет является дубликатом для `get_name()`, и нам достаточно написать только одну функцию (и назвать её, например, `chars_to_byte()`).

**Comment by beskaska** [comment]
Неактуально
