### ISSUE TITLE
Написать функцию get_exec_code()

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#20]
### Прототип:
``` c
int    *get_exec_code(t_bot *bot, size_t fd);
```

### Todo
- [ ] написать базовый тест
- [ ] написать саму функцию
- [ ] написать дополнительные тесты

### Описание
Данная функция должна прочитать исполняемый код "чемпиона" из указанного файлового дескриптора, перевести его в соответствующий байт код ([см. Вики](https://github.com/CptnGreen/Corewar/wiki/%D0%98%D0%B7-%D0%B0%D1%81%D1%81%D0%B5%D0%BC%D0%B1%D0%BB%D0%B5%D1%80%D0%B0-%D0%B2-%D0%B1%D0%B0%D0%B9%D1%82-%D0%BA%D0%BE%D0%B4#%D0%9A%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B9)) и записать полученный байт-код и его размер в соответствующие переменные структуры.
