### ISSUE TITLE
Написать функцию print_byte_code()

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#4]
**Прототип**
`int	print_byte_code(char *file_name, t_bot *bot)`

**TO-DO**
- [x] проверить расширение файла
- [x] создать и открыть файл
- [x] вставить magic_header
- [x] вставить все символы из массива bot_name структуры t_bot*
- [x] вставить нули-разделители
- [x] вставить каждый байт, exec_size структуры t_bot*, по-отдельности
- [x] вставить все символы из массива comment структуры t_bot*
- [x] вставить нули-разделители
- [x] вставить ровно exec_size символов из массива exec_code структуры t_bot*
- [x] закрыть файл
- [x] написать общий тест для `get_byte_code()`

**Описание**
Функция должна принимать информацию о боте в виде структуры и записать все данные в определенном порядке в файл с названием _*file_name_, но заменить расширение ".s", на расширение ".cor".

**Алгоритм**
- создать и открыть файл для записи (если файл существует - перезаписать);
- вставить результат работы функции `get_magic_header()`;
- вставить все символы из массива bot_name структуры _t_bot*_;
- вставить нули-разделители;
- побайтно вставить _exec_size_ (4 байта == long) структуры _t_bot*_;
- вставить все символы из массива _comment_ структуры _t_bot*_;
- вставить нули-разделители;
- вставить ровно _exec_size_ символов из массива _exec_code_ структуры _t_bot*_;
- закрыть файл для записи.

**Comment by ellyellyd** [comment]
Test comment

**Comment by beskaska** [comment]
Я изменил описание функции в соответствии с новой структурой ассемблера
