### ISSUE TITLE
Написать функцию get_name()

### ISSUE THREAD

**Issue by CptnGreen** [CptnGreen/Corewar#6]
### Todo

- [x] создать модуль ceedling (CptnGreen)
- [x] написать базовый тест (CptnGreen)
- [ ] написать больше тестов
- [ ] написать саму функцию

### Описание

Функция должна принимать строку с именем бота и возвращать строку с байт-кодом этого имени, которую затем можно будет сшить с другими фрагментами полного байт-код бота. 

В возвращаемую строку не нужно добавлять заполнящие нули, эти фрагменты будет генерировать другая функция. 

Прототип:
``` c
char	*get_name(char const *name);
```

**Comment by CptnGreen** [comment]
Этот тикет закрываю, так как это функция дублирует `chars_to_bytes()`
